---
title: "example_code"
author: "Lauren Harris"
date: "3/7/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# required packages
library(here)
library(purrr)
library(RColorBrewer)
library(tidyverse)

# import the function 
source(here("scripts", "tif_to_gif.R"))
```

```{r}
# example for a single species
tif_to_gif(prefix = "adenfasc", output_name = "landis", output_location = here("data", "output_data"), frames_per_sec = 1, path_to_folder = here("data"), colors = "Greens")
```

```{r}
# example for multiple species

# file path 
my_path <- here("data")
# yours might look something like this on the bren computers: "H:/ESM215/ex7/landis_II/burtonmesa/modern-fire/output/max-spp-age/"

# define species and scenarios of interest
species_list <- c("adenfasc", "ceanramu")
firescenarios <- c("lowlow", "lowhigh", "highlow", "highhigh")

# run for list of species
pmap(list(prefix = species_list), output_location = here("data", "output_data"), .f = tif_to_gif, output_name = "landismodernfire", frames_per_sec = 1, path_to_folder = my_path, colors = "Greens", list(suffix = firescenarios))

# run for list of fire scenarios
pmap(prefix = "ceanramu", output_location = here("data", "output_data"), .f = tif_to_gif, output_name = "landismodernfire", frames_per_sec = 1, path_to_folder = my_path, colors = "Greens", list(suffix = firescenarios))

# run for fire severity
pmap(prefix = "severity", output_location = here("data", "output_data"), .f = tif_to_gif, output_name = "landismodernfire", frames_per_sec = 1, path_to_folder = my_path, colors = "Greens", list(suffix = firescenarios))
```

