---
title: "example_without_fx"
author: "Lauren Harris"
date: "3/7/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(raster)
library(gtools)
library(here)
library(raster)
library(tmap)
library(purrr)
library(RColorBrewer)
```

Settings
```{r}
# the prefix of the imported files of interest
prefix <- "adenfasc"
# the prefix of the output file name(s)
output_name <- "landis"
# the file path to the input data
path_to_folder <- here("data")
# the file path to the output data
output_location <- here("data", "output_data")
# speed of GIF (in frames per second)
frames_per_sec <- 1
# color palette of GIF
my_colors <- "Purples"
```

Run code
```{r}
# find files that start with the prefix and end with .tif
pattern_here <- c(paste0(prefix, ".*", ".tif$"))

# read in the file paths
tif_list <- gtools::mixedsort(list.files(path = here("data"), pattern=pattern_here, all.files = TRUE, full.names = TRUE,), decreasing = TRUE)

# convert all to raster
lapply(tif_list, raster)

# stack and brick the TIFs
all_tifs <- raster::stack(tif_list)
b_tifs <- raster::brick(all_tifs)

# animate the TIFs
anim <- tmap::tm_shape(b_tifs) + tmap::tm_raster(palette = my_colors) + tmap::tm_facets(nrow = 1, ncol = 1)
```

Export gif
```{r}
# name your file (automatic based on settings)
output_file_name <- paste0(output_name, "_", prefix, ".gif")

# export
tmap_animation(anim, fps = frames_per_sec, filename = paste0(output_location, "/", output_file_name))
```

